version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    ignore:
      - dependency-name: "@expo/*"
      - dependency-name: "expo*"
      - dependency-name: "react*"
      - dependency-name: "\*"
        update-types: ["version-update:semver-patch"]
    groups:
      deps-prod:
        dependency-type: "production"
      deps-dev:
        dependency-type: "development"
