version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
    commit-message:
      prefix: ":arrow_up:"
    labels:
      - "⬆️ dependencies"
    groups:
      deps:
        patterns: ["*"]
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*expo*"
      - dependency-name: "*react*"
      - dependency-name: "@shopify*"
      - dependency-name: "tailwindcss"
      - dependency-name: "@tanstack/react-query"
