name: "Setup repository"
description: "Dangerously checkout, install node, bun, and packages with frozen-lockfile"

inputs:
  node-version:
    description: "Version of node to use, e.g. 20.x"
    required: true
    default: "20.x"
  bun-version:
    description: "Version of bun to use, e.g. 1.0.x"
    required: true
    default: "latest"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        # Checkout from PR code so we can run this from forks
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 2
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ inputs.bun-version }}
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install dependencies
      run: bun i --frozen-lockfile
      shell: bash
