name: 📄 Docs Improvement
description: Help us write better docs!
labels: ["📄 docs"]
body:
    - type: markdown
      attributes:
          value: Thanks for taking the time to file a docs improvement request! Please fill out this form as completely as possible.
    - type: textarea
      id: problem
      attributes:
          label: How can Elrax's documentation be improved?
          description: |-
              Provide a link to the documentation and describe how it could be improved. In what ways is it incomplete, incorrect, or misleading?

              If you have suggestions on exactly what the new docs should say, feel free to include them here. Or alternatively, make the changes yourself and create a pull request instead.
          placeholder: |-
              These functions has no documentation at all. This makes it difficult to know how to use them.
      validations:
          required: true
