account_id = "82fd74a54708ed514403791b191174b5"
compatibility_date = "2024-05-13"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]

[env.dev]
vars = { ENVIRONMENT = "dev" }
[[env.dev.d1_databases]]
binding = "DB"
database_name = "dev-db"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "migrations"
[[env.dev.r2_buckets]]
binding = "BUCKET"
bucket_name = "bucket-dev"

[env.staging]
name = "elrax-api-staging"
workers_dev = false
vars = { ENVIRONMENT = "staging" }
route = { pattern = "api-staging.elrax.com", custom_domain = true }
[[env.staging.d1_databases]]
binding = "DB"
database_name = "elrax-db-staging"
database_id = "aae4d36f-1ab7-4215-8665-b34012e5bdf9"
migrations_dir = "migrations"
[[env.staging.r2_buckets]]
binding = "BUCKET"
bucket_name = "elrax-staging"

[env.production]
name = "elrax-api-production"
workers_dev = false
vars = { ENVIRONMENT = "production" }
route = { pattern = "api.elrax.com", custom_domain = true }
[[env.production.d1_databases]]
binding = "DB"
database_name = "elrax-db-production"
database_id = "6fdf3e76-2047-4de8-aee8-2c136ff02881"
migrations_dir = "migrations"
