compatibility_date = "2024-05-12"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]

[env.dev]
vars = { ENVIRONMENT = "dev" }
[[env.dev.r2_buckets]]
binding = "BUCKET"
bucket_name = "bucket-dev"

[env.staging]
name = "elrax-api-staging"
workers_dev = false
vars = { ENVIRONMENT = "staging" }
route = { pattern = "api-staging.elrax.com", custom_domain = true }
[[env.staging.r2_buckets]]
binding = "BUCKET"
bucket_name = "elrax-staging"

[env.production]
name = "elrax-api-production"
workers_dev = false
vars = { ENVIRONMENT = "production" }
route = { pattern = "api.elrax.com", custom_domain = true }
