account_id = "82fd74a54708ed514403791b191174b5"
compatibility_date = "2023-05-02"
main = "src/index.ts"
workers_dev = true

[env.dev]
kv_namespaces = []
[[env.dev.d1_databases]]
binding = "DB"
database_name = "dev-db"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "migrations"
