name: "CLA Assistant"

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions:
  actions: write
  pull-requests: write
  statuses: write

jobs:
  cla-assistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read and hereby sign the Contributor License Agreement.') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_GITHUB_TOKEN }}
        with:
          path-to-signatures: "elrax/v1/cla.json"
          path-to-document: "https://elrax.com/cla"
          branch: "main"
          allowlist: dependabot[bot],github-actions[bot]
          remote-organization-name: elrax
          remote-repository-name: cla-signatures
          create-file-commit-message: "chore: creating file for storing CLA Signatures"
          signed-commit-message: "chore: $contributorName has signed the CLA in $owner/$repo"
          # custom-notsigned-prcomment: "pull request comment with introductory message to ask new contributors to sign"
          custom-pr-sign-comment: "I have read and hereby sign the Contributor License Agreement."
          custom-allsigned-prcomment: "All Contributors have signed the CLA."
          lock-pullrequest-aftermerge: false
