name: Deployment Web

concurrency:
  group: production
  cancel-in-progress: false

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/deployment-web.yml"
      - "apps/web/**"

jobs:
  deploy-web-production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          # Checkout from PR code so we can run this from forks
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"
      - name: Install dependencies
        run: bun i -g node-gyp-build && bun i --frozen-lockfile

      - name: Build apps
        run: bun build

      - name: Deploy landing
        uses: cloudflare/pages-action@v1
        with:
          wranglerVersion: "3"
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: ./apps/web/landing/
          directory: ./dist/
          projectName: elrax

      - name: Deploy blog
        uses: cloudflare/pages-action@v1
        with:
          wranglerVersion: "3"
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: ./apps/web/blog/
          directory: ./dist/
          projectName: elrax-blog

      - name: Deploy comics
        uses: cloudflare/pages-action@v1
        with:
          wranglerVersion: "3"
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: ./apps/web/comics/
          directory: ./dist/
          projectName: elrax-comics
