name: Deployment

concurrency:
  group: staging
  cancel-in-progress: false

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Apply DB migrations
        env:
          TURSO_CONNECTION_URL: ${{ vars.TURSO_CONNECTION_URL }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
        run: |
          cd ./apps/api/
          bun db:apply

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: ./apps/api/
          packageManager: pnpm
          environment: staging
        env:
          CF_BUCKET_NAME: elrax-staging
          CF_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          CF_ACCESS_KEY_ID: ${{ secrets.CF_ACCESS_KEY_ID }}
          CF_SECRET_ACCESS_KEY: ${{ secrets.CF_SECRET_ACCESS_KEY }}
          FACEBOOK_APP_ID: ${{ vars.FACEBOOK_APP_ID }}
          FACEBOOK_APP_SECRET: ${{ secrets.FACEBOOK_APP_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          TURSO_CONNECTION_URL: ${{ vars.TURSO_CONNECTION_URL }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Create build
        uses: expo/expo-github-action/preview@v8
        with:
          # temporary iOS only, replace with "all" when needed
          command: eas build -e=staging -p=ios --non-interactive
          working-directory: ./apps/mobile/
          comment: false

      - name: Create update
        uses: expo/expo-github-action/preview@v8
        id: preview
        with:
          command: eas update --auto --channel=staging
          working-directory: ./apps/mobile/
          comment: false
