name: Deployment

concurrency:
  group: staging
  cancel-in-progress: false

on:
  push:
    branches:
      # TODO: Change this to main
      - feat/eas-ci

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: ./apps/api/
          packageManager: pnpm
          environment: staging

  update-mobile:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Create preview
        uses: expo/expo-github-action/preview@v8
        id: preview
        with:
          command: eas update --auto
          working-directory: ./apps/mobile/
          comment: false
