name: "Code lint"

on:
  merge_group:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Checkout from PR code so we can run this from forks
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"
      - name: Install dependencies
        run: bun i -g node-gyp-build && bun i --frozen-lockfile

      - name: Copy .env and code lint
        run: cp .env.example .env && bun lint
