name: "Code lint"

on:
  merge_group:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - name: Copy .env and code lint
        run: cp .env.example .env && pnpm lint
