name: Release

concurrency:
  group: release
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (major/minor/patch)"
        required: true
        default: "patch"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ vars.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"
      - name: Install dependencies
        run: bun i --frozen-lockfile

      - name: Set git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Create changelog and release
        run: bun run release --ci -i=${{ github.event.inputs.version }} --git.pushArgs=--force
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
